# === Pipeline configuration ===
random_state: 42
test_size: 0.2
target_col: "Survived"        # <-- change to your dataset's target/label column
id_columns: []              # optional columns to drop (e.g., IDs)
# path to your dataset (CSV or Excel). For Excel, specify the sheet with excel_sheet (optional)
dataset_path: "C:/Users/lenovo/Desktop/ml-pipeline/dataset/train.csv"
excel_sheet: null

# Model space to try
models:
  logistic_regression:
    type: "logistic_regression"
    param_grid:
      C: [0.1, 1.0, 10.0]
      penalty: ["l2"]
      solver: ["lbfgs"]
      max_iter: [1000]
  decision_tree:
    type: "decision_tree"
    param_grid:
      criterion: ["gini", "entropy"]
      max_depth: [null, 5, 10, 20]
      min_samples_split: [2, 5, 10]
  random_forest:
    type: "random_forest"
    param_grid:
      n_estimators: [100, 200]
      max_depth: [null, 5, 10, 20]
      min_samples_split: [2, 5, 10]
